# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  #contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
#zh:
#  languageCode: zh-Hans # 语言代码：zh-Hans
#  contentDir: content/zh
# contentDir： content/zh
#  title: Chinese website title...
# title：中文网站标题...
#  params: # 参数：
#    description: Site description in Chinese...
# description： 中文网站描述...
#  menu: # 菜单：
#    main:
# 主要：
#      - name: 传
# - name： 传
#        url: '#about'
# 网址： '#about'
#        weight: 1
# 重量： 1
